name: flutter_post
description: "Your mini social-media stop shop."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_storage: ^12.4.1
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  hive_ce: ^2.9.0
  hive_ce_flutter: ^2.2.0
  internet_connection_checker: ^3.0.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1
  collection: ^1.19.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  custom_lint: ^0.7.2
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  hive_ce_generator: ^1.8.2
  json_serializable: ^6.9.3
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
